-- Switches auth identity from email to an admin-managed "login ID", and adds
-- an is_admin flag. Real email addresses are never used — each user's
-- Supabase Auth email is a synthetic "<login_id>@login.internal" value
-- generated by the app, never sent mail.

alter table public.profiles
  add column login_id text unique,
  add column is_admin boolean not null default false;

-- profiles readable by room members already covers normal lookups; add a
-- self-read fallback isn't needed since "id = auth.uid()" is already in that
-- policy's OR clause.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, login_id, is_admin)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'login_id'),
    new.raw_user_meta_data->>'login_id',
    coalesce((new.raw_user_meta_data->>'is_admin')::boolean, false)
  );
  return new;
end;
$$;
